# Linear algebra

## Example

$$\boldsymbol{A} \vec{x} = \vec{b}$$

In [4]:
import numpy as np
a = np.random.randn(5, 5)
a

array([[ 1.25725419, -0.27987616, -0.96345815,  1.21187748,  0.13909087],
       [ 0.80170155, -0.06610207, -0.22606558, -0.40012405, -1.07144688],
       [-1.59939152, -0.85849629,  0.03425393, -0.95655549, -1.04363851],
       [-1.5786452 , -0.30568397, -0.98579524,  0.75086196, -1.4432597 ],
       [-1.13501904, -0.40245116,  0.37028886, -2.78680169,  0.30188347]])

In [5]:
b = np.ones((5, 1))
b

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [10]:
x = np.linalg.solve(a=a, b=b)
x

array([[ 0.24288223],
       [-0.7658774 ],
       [-1.20706016],
       [-0.53462025],
       [-0.2500037 ]])

In [9]:
np.matmul(a, x)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])